### ISSUE TITLE
Error: unresolved name `window_style::CLOSE` in examples

### ISSUE THREAD

**Issue by msvbg** [jeremyletang/rust-sfml#112]
The examples tell you to do this to open a window:

```rust
use sfml::graphics::{RenderWindow};
use sfml::window::{ContextSettings, VideoMode, window_style};

...

let mut window = match RenderWindow::new(
  VideoMode::new_init(800, 600, 32),
  "SFML Example",
  window_style::CLOSE,
  &ContextSettings::default()) {
    Some(window) => window,
    None => panic!("Cannot create a new Render Window.")
};
```

But this throws an error: unresolved name `window_style::CLOSE`.

Using `rustc 1.6.0-beta.3`.

**Comment by crumblingstatue** [comment]
The tests pass for the examples in both `examples/` and the example in the documentation.
My guess is that you are using 0.9.3, but reading the examples from git master.
The API has changed since 0.9.3, and a new version hasn't been published yet.

The examples for 0.9.3 can be found [here](https://github.com/jeremyletang/rust-sfml/tree/v0.9.3/examples).

**Comment by msvbg** [comment]
Ok, thanks!
