### ISSUE TITLE
Better documentation and support for finding native libs on windows

### ISSUE THREAD

**Issue by crumblingstatue** [jeremyletang/rust-sfml#138]
1. [ ] Determine where the SFML libraries should be installed for each of the GNU and MSVC toolchains
2. [ ] Document it
3. [ ] Add support in the build scripts for detecting and using the libraries installed in these locations.

Additional things that can be done
- [ ] Document #137

**Comment by crumblingstatue** [comment]
Mentioning #165 for reference.

**Comment by TheJare** [comment]
I just got a rust-sfml window running on Windows with MSVC. It was painful because the documentation for building sfml/csfml with CMake is pretty much nonexistent to begin with.

Apparently, CSFML needs to be built as dynamic libraries, but use SFML as static libraries. So this is what I did, ending up with the following:

- sfml-XXX-s.lib files
- csfml-XXX.lib files
- csfml-XXX-2.dll files

I had to rename the sfml-XXX-s.lib to remove the "-s" suffix from the name, because this crate wants the clean name. I don't know if this suffix is something peculiar to the CMake build of SFML or what.

But, thinking about it more... if CSFML are DLLs containing a statically linked SFML, and the rust-sfml crate only interfaces with CSFML, then rust-sfml should not need to link with SFML at all, since it does not use it. Is this correct?

**Comment by crumblingstatue** [comment]
> But, thinking about it more... if CSFML are DLLs containing a statically linked SFML, and the rust-sfml crate only interfaces with CSFML, then rust-sfml should not need to link with SFML at all, since it does not use it. Is this correct?

This might be true on windows, you could test it if you have the time. It isn't true on linux, where csfml links to sfml dynamically.

In the long term, I'm planning to skip CSFML entirely, and use bindgen to bind directly to SFML, but I don't know yet what will come of that.

**Comment by lernrust** [comment]
Hi. I have 2 problems :(

SFML 2.4.0 
CSFML 2.4.0
32bit

E:\Users\Admin\projects\rust-sfml> cargo build --verbose
       Fresh bitflags v1.0.1
       Fresh sfml-build v0.2.0 (file:///E:/Users/Admin/projects/rust-sfml/ffi/sfml-build)
       Fresh csfml-system-sys v0.4.0 (file:///E:/Users/Admin/projects/rust-sfml/ffi/csfml-system-sys)
       Fresh csfml-window-sys v0.4.0 (file:///E:/Users/Admin/projects/rust-sfml/ffi/csfml-window-sys)
       Fresh csfml-audio-sys v0.4.0 (file:///E:/Users/Admin/projects/rust-sfml/ffi/csfml-audio-sys)
       Fresh csfml-graphics-sys v0.4.0 (file:///E:/Users/Admin/projects/rust-sfml/ffi/csfml-graphics-sys)
   Compiling sfml v0.14.0 (file:///E:/Users/Admin/projects/rust-sfml)
     Running `rustc --crate-name sfml src\lib.rs ...

... error: linking with `link.exe` failed: exit code: 1181

... error: Could not compile `sfml`.

CSFML_HOME and SFML_HOME is fine.

other msvc c++ projects with sfml work fine with 32bit.

...

SFML 2.4.0 
CSFML 2.4.0
64bit

It "work":
E:\Users\Admin\projects\rust-sfml> cargo build
...
Finished dev [unoptimized + debuginfo] target(s) in 6.43 secs

E:\Users\Admin\projects\rust-sfml> cargo run --example pong
   Compiling sfml v0.14.0 (file:///E:/Users/Admin/projects/rust-sfml)
    Finished dev [unoptimized + debuginfo] target(s) in 0.87 secs
     Running `target\debug\examples\pong.exe`
error: process didn't exit successfully: `target\debug\examples\pong.exe` (exit code: 3221225781)

I copied CSFML\bin to target\debug\examples and try again:

    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target\debug\examples\pong.exe`
Failed to open sound file "resources/ball.wav" (couldn't open stream)
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src\libcore\option.r
note: Run with `RUST_BACKTRACE=1` for a backtrace.
error: process didn't exit successfully: `target\debug\examples\pong.exe` (exit code: 101)

Tryed copied sfml bins, but still exit code: 101. What i do wrong?

**Comment by TheJare** [comment]
So it should be possible to skip the reference to sfml libraries in windows only? Can that be checked in the various build.rs ffi files that emit both libraries (or the sfml-build lib.rs file itself)? (I don't know about that stuff, learning as I go)

**Comment by crumblingstatue** [comment]
> So it should be possible to skip the reference to sfml libraries in windows only? Can that be checked in the various build.rs ffi files that emit both libraries (or the sfml-build lib.rs file itself)? (I don't know about that stuff, learning as I go)

Yes, this should be possible using build scripts. One could check the value of [`CARGO_CFG_TARGET_OS`](http://doc.crates.io/environment-variables.html), and do something different if it's `windows`.

**Comment by metavee** [comment]
I just wanted to document some differences I found between what I had to do and what was in the wiki.

For reference, I'm on 64-bit Windows 10, with `rustc` 1.27.2. And since I followed the installation instructions in the second edition of the Rust book, I'm using MSVC, not GCC.

- there were no `*.a` files, only `*.lib`
- the path for the `*.lib` files was `%UserProfile%\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\x86_64-pc-windows-msvc\lib`
- I also needed to copy `openal32.dll` from `SFML\bin` to get the pong example to run (I assume it's a dependency for SFML audio module).

**Comment by Kiiyya** [comment]
For anyone coming across this issue, there's a wiki entry which worked perfectly for me: https://github.com/jeremyletang/rust-sfml/wiki/Windows And I was too blind to find it at first, so I'm putting this here in case someone else stumbles across this again.

**Comment by crumblingstatue** [comment]
Rust-sfml is now statically linked on windows, with the sole exception of `openal32.dll` so this should be more or less a solved issue.

I'm closing, but if anyone still has issues, feel free to open another issue.
