### ISSUE TITLE
Question: Using Colors as a const

### ISSUE THREAD

**Issue by williamscs** [jeremyletang/rust-sfml#155]
How do you declare a const Color? I'm not sure if it's the rust language itself I'm misunderstanding, but I'm having a heck of a time trying to declare this.

I don't seem to be able to reference csfml_graphics_sys as an extern crate, so I can't use the struct initialization using sfColor. Attempting to use new_rgb/a are throwing errors if I attempt to create one with those since they aren't considered constructors. Am I missing something?

**Comment by crumblingstatue** [comment]
> I don't seem to be able to reference csfml_graphics_sys as an extern crate, so I can't use the struct initialization using sfColor.

Did you also add `csfml-graphics-sys` as a dependency in `Cargo.toml`? You need to do that if you want to use it.

But it's not intended for users to have to use the csfml-sys crates for normal usage, so this is considered a bug. It's fixed in #153, but has not been merged yet.

**Comment by williamscs** [comment]
I did, but I got an error saying I couldn't link against the library twice, or something similar. I'm using the github repo as the source, rather than the 0.11 crate, if that makes a difference.

But you mention that users shouldn't be using csfml-sys... is there a way to declare a Color as a const outside of a function? It looked like the only way was to create an sfColor struct. If I try something like:
`const TARGET_COLOR: Color = Color::new_rgba(67u8, 165u8, 87u8, 255u8);`
then I get:
`error[E0015]: calls in constants are limited to struct and enum constructors`

Is this just something I can't do?

**Comment by crumblingstatue** [comment]
> I did, but I got an error saying I couldn't link against the library twice, or something similar.

One way this could happen is if your crate and rust-sfml use different versions of `csfml-graphics-sys`. Are you sure that's not the case? Try declaring the version as `"*"`, and removing `Cargo.lock`.

> But you mention that users shouldn't be using csfml-sys... is there a way to declare a Color as a const?

Not currently. The `const fn` feature in Rust, which would allow `Color::new_rgba` to be used in this context is unstable.

The refactorings in #153 include a fix for this by directly declaring the fields of `Color` instead of using `sfColor` internally. But this hasn't been merged. You could use the [sfml24-graphics](https://github.com/jeremyletang/rust-sfml/tree/sfml24-graphics) branch if you want to test this feature.

If you want to use the master branch and also take advantage of this fix, I _could_ backport it, but I would rather avoid backporting individual commits if possible.

**Comment by williamscs** [comment]
No need to backport at all! I'm working on a proof of concept for work and I already have the workaround. This is my first project using rust and I'm wrapping my head around the whole thing.

I'll look into the version conflict. Thanks a ton for your help; had no idea about const fn. Also, this is good stuff! This library has been very helpful in getting stuff into a window easily for a newbie to the language.
