### ISSUE TITLE
[Question] Example project(s)?

### ISSUE THREAD

**Issue by woubuc** [jeremyletang/rust-sfml#191]
Do example project repositories (or repositories of projects using Rust-SFML) exist that work on both Windows and Linux? I have a project set up with SFML on my Windows PC but my friend works on Linux and he cannot get it to work. And vice versa, when he sets something up I can't get it to build properly. So it would be really helpful to check out some repos that are working for both platforms, because using just the information on the wiki is not at all enough to get up and running with Rust-SFML.

If there's more setup information than the wiki in this repo, please direct me there cause I cannot find much more on the topic of installing and linking SFML.

**Comment by crumblingstatue** [comment]
All the [examples](https://github.com/jeremyletang/rust-sfml/tree/master/examples) should work for all supported platforms.

But the problem seems to be with properly installing SFML on your local system, which has nothing to do with how you set up a specific project.

If you have a specific problem, you could try posting it here, but I don't use Windows, so the help I can provide is limited.

**Comment by woubuc** [comment]
Thanks for the feedback. It was indeed related to installing SFML, as it turned out building from source didn't work but after removing that and installing the libs from apt-get it worked fine.
