### ISSUE TITLE
from_file() should use PathBuf

### ISSUE THREAD

**Issue by DuckerMan** [jeremyletang/rust-sfml#201]
Hello, I think that from_file functions should use `PathBuf` struct because this is more idiomatic

**Comment by crumblingstatue** [comment]
This is more complicated than it seems on the surface.
Internally, we are using `CString` to pass a null terminated string to CSFML.
I don't know of a good way to convert a `Path` to a `CString` without going through hoops.

The main argument I can think of against using `&str` in the API is that it doesn't allow non-UTF-8 paths.
But I don't even know what kind of encoding SFML expects, if any.

This should definitely be researched more.

**Comment by DuckerMan** [comment]
@crumblingstatue We can use that: ``` CString::new(path.as_os_str().to_str().unwrap()).unwrap() ```

**Comment by crumblingstatue** [comment]
@DuckerMan Well, just look at that code carefully. 
It calls `to_str()`, we're back to square one. If it has to be valid as a &str, we might as well take &str.
Otherwise, why lie in the API?

**Comment by DuckerMan** [comment]
`CString::new(osstr.to_string_lossy().as_bytes()).unwrap()`

Or we can do so

**Comment by crumblingstatue** [comment]
I don' think calling `to_string_lossy` is a good idea, as it could silently make lossy paths. I think it's better to panic. At least it's clear that something is wrong if the user gets a panic, rather than wondering why the path isn't resolving.

Anyway, I don't think we even need the intermediary string. I don't think `CString` has the UTF-8 requirement that `String` does.

**Comment by crumblingstatue** [comment]
Okay, so here's the problem. SFML uses `std::string`, which is basically a byte vector under the hood. But `OsStr` can have a representation that's different than a byte vector. I don't think `Path` is a good choice here. However, we could lift the UTF-8 requirement by accepting `AsRef<[u8]>` or something similar instead of `&str`.

**Comment by crumblingstatue** [comment]
Since using PathBuf is not a good replacement, and there hasn't been further activity, I'm closing this.
