### ISSUE TITLE
Progress and implementation of RcSprite

### ISSUE THREAD

**Issue by Aelerinya** [jeremyletang/rust-sfml#204]
I'd like to know. What prevents RcSprite from being published in a new version of rust-sfml ?
I've been struggling for two days over storing a Texture and a Sprite side by side, and I think RcSprite is what I need to not go insane in developing using rust-sfml.

Is it safe to copy the implementation of the branch rcsprite in my code or is it still an incomplete prototype ?
What could I do to help develop this feature ?

**Comment by crumblingstatue** [comment]
I'd like to avoid duplicating a lot of code just to have a version of sprite that can work with `Rc<Texture>`. I just haven't figured out the best way to minimize the code duplication.

Since I am not actively working on rust-sfml at present, I'm open to taking pull requests if someone comes up with a decent design.

**Comment by crumblingstatue** [comment]
#298 should address the need for this, so I'm closing.
