### ISSUE TITLE
[Question] RenderStates moved around rather than references.

### ISSUE THREAD

**Issue by pjfordham** [jeremyletang/rust-sfml#220]
I think RenderStates should be passed arounf via a constant refereance rather than moved. 

I have a Drawable which makes calls to various sub components draw_with_renderstates methods and I want to use the same RenderStates object. As this is moved I have to create a copy for the second call.

What's the rationale behind this being moved rather than references. Sorry if my terminology is wrong, I'm new to Rust.

**Comment by crumblingstatue** [comment]
The whole rendering API is kinda complicated.
Even if I made the public API take it by reference, it would still copy due to how it works internally.
I don't actually know if it would ultimately result in less or more copying if changed that way.
I guess it would reflect the original C++ API better.
But it would take work rewriting it, and I don't know if it's ultimately worth it.
`RenderStates` is `Copy`, so you don't have to do anything copying manually yourself.

**Comment by pjfordham** [comment]
OK. I was using an older version where RenderStates wasn't Copy. Thanks for the quick reply.

**Comment by crumblingstatue** [comment]
Just a heads up, I reworked `RenderStates`, so it's now passed by immutable borrow wherever possible.
7b556eb3ed970d68e857b9b35756fd198109670a
