### ISSUE TITLE
window::Handle has incorrect type on platforms other than Linux/BSD

### ISSUE THREAD

**Issue by arm32x** [jeremyletang/rust-sfml#243]
`sf::WindowHandle` is different on each platform (for example, it's `HWND` on Windows and `unsigned long` on Linux/BSD), but `window::Handle` in this crate is always a `c_ulong`, regardless of platform. This makes it impossible to use `Window::from_handle` on any platform other than Linux/BSD.

Definition of `window::Handle`:
https://github.com/jeremyletang/rust-sfml/blob/e4f1149554735f87471c75cbb2424d81f05de678/src/window/window.rs#L10-L12
https://github.com/jeremyletang/rust-sfml/blob/e4f1149554735f87471c75cbb2424d81f05de678/src/ffi/window.rs#L1158

[Definition of `sf::WindowHandle`](https://github.com/SFML/SFML/blob/2f11710abc5aa478503a7ff3f9e654bd2078ebab/include/SFML/Window/WindowHandle.hpp#L40-L70):
```cpp
#if defined(SFML_SYSTEM_WINDOWS)

    // Window handle is HWND (HWND__*) on Windows
    typedef HWND__* WindowHandle;

#elif defined(SFML_SYSTEM_LINUX) || defined(SFML_SYSTEM_FREEBSD) || defined(SFML_SYSTEM_OPENBSD)

    // Window handle is Window (unsigned long) on Unix - X11
    typedef unsigned long WindowHandle;

#elif defined(SFML_SYSTEM_MACOS)

    // Window handle is NSWindow or NSView (void*) on Mac OS X - Cocoa
    typedef void* WindowHandle;

#elif defined(SFML_SYSTEM_IOS)

    // Window handle is UIWindow (void*) on iOS - UIKit
    typedef void* WindowHandle;

#elif defined(SFML_SYSTEM_ANDROID)

    // Window handle is ANativeWindow* (void*) on Android
    typedef void* WindowHandle;

#elif defined(SFML_DOXYGEN)

    // Define typedef symbol so that Doxygen can attach some documentation to it
    typedef "platform-specific" WindowHandle;

#endif
```

**Comment by crumblingstatue** [comment]
Currently raw bindings are generated by running bindgen manually. I run it manually on my Linux system.
It looks like this is one of the rare cases where that causes problems with this library.

Here are some options on how to solve this:
1. Manually patch this one value for windows and don't forget to keep doing that every time we regenerate with bindgen. This might be the quickest and most painless solution.
2. Use bindgen as a library. This is technically the most correct solution, as it would always generate the right bindings for the target platform. The main problems with this solution is that it increases compile times and it requires libclang installed on the host machine. I couldn't even figure out how to install libclang on windows last time I had to deal with bindgen.
3. Completely rewrite bindings manually. I would really prefer not having to do this, but it could work out, especially since we now vendor CSFML, enabling us to simplify some things we need to bind. But it would still be a ton of work and error prone.

**Comment by crumblingstatue** [comment]
I'm currently investigating the feasibility of option 2. I'll report back when ready.

**Comment by crumblingstatue** [comment]
There is now an experimental branch where bindgen is used as a library.
https://github.com/jeremyletang/rust-sfml/tree/bindgen-lib

**Comment by crumblingstatue** [comment]
I merged the bindgen-lib branch after testing it works on windows. I think it's the way forward.
I'm going to try to add the SFML OpenGL example to test platform window handles.

**Comment by crumblingstatue** [comment]
I added an OpenGL example, but it turns out that doesn't need a raw window handle.

Please test if latest git version works for your use case, and feel free to close this issue if it does.

**Comment by crumblingstatue** [comment]
This should be fixed now, but feel free to reopen if that's not the case.
