### ISSUE TITLE
Window::keyboard is private, when it should be public.

### ISSUE THREAD

**Issue by MrMagician** [jeremyletang/rust-sfml#318]
I am currently writing a test project using _rust-sfml_. And I'm aware that using the event system is a very messy way to do realtime input. However, there appears to be no equivalent to _sf::Keyboard_. The _Window_ module for these bindings appears to have what I need, including: _clipboard_, _joystick_, _mouse_, _sensor_, and _touch_. But there doesn't appear to be any keyboard module. As a test i wrote this code:

`use sfml::window::keyboard`

which gave me this error:

`error[E0603]: module "keyboard" is private`

It looks like you may have forgotten to label this module/struct as public.

Thank you for your time.

**Comment by crumblingstatue** [comment]
Using the event system is the recommended way to do input, because it responds to the window events. The method for directly querying keyboard input ignores whether the window is focused, which might not be what you want.

Regardless, if you're looking for Keyboard::isKeyPressed, then you want this: https://docs.rs/sfml/0.20.0/sfml/window/enum.Key.html#method.is_pressed

**Comment by MrMagician** [comment]
Alright, thank you so much!
