### ISSUE TITLE
Consider panicking instead of returning None on allocation failures

### ISSUE THREAD

**Issue by tVoss** [jeremyletang/rust-sfml#34]
I'm not sure if other object behave in this manor, but for something as simple as a shape constructor, is returning Option the best option (no pun intended)? As far as I can tell, the only reason None would be returned would be due to an allocation error, and that would imply the program is out of memory. If that's the case, then there are a lot bigger problems at hand that shouldn't be dealt with wherever a shape is getting created. I feel a fail!() if the shape is null when created would make more sense, but that's just my opinion.

**Comment by Ape** [comment]
I think we should obey [the official guidelines for error handling](http://doc.rust-lang.org/nightly/style/errors/signaling.html). Any possible error case caused by an external obstruction should use a Result. If the return value is considered a success even when there is no value then it should be an Option. Panics should be used for contract violations and "impossible situations".

Allocation failures are not successes, but they are certainly possible and should be checked for. I think we should use a Result for these cases. Also something like failing to create a new window should use a Result instead of an Option.

**Comment by crumblingstatue** [comment]
@Ape 
> I think we should obey the official guidelines for error handling.

Quoting official guidelines for error handling:
> An error is catastrophic if there is no meaningful way for the current task to continue after the error occurs.
Catastrophic errors are extremely rare, especially outside of libstd.
Canonical examples: *out of memory*, stack overflow.

> For catastrophic errors, *panic*

According to the official guidelines, we should panic on out of memory.

This is also how the rust standard library behaves.

**Comment by Ape** [comment]
@crumblingstatue, are these allocation errors absolutely fatal? If so, then yes we should panic on them. If it's possible to cancel the allocation, but continue running the application, then it's not catastropic. I'm not so familiar with this specific situation, but I interpret the error semantics like this. The out of memory and stack overflow cases in the example are rust internal memory handling and thus fatal.

**Comment by jeremyletang** [comment]
hi guys, If you want to remove option type on constructors I'm okay with this, feel free to propose changement which follows the Rust guideline.
Or any improvement for the library, Just open an issue like this before and we can discuss about it.

**Comment by crumblingstatue** [comment]
ref https://github.com/jeremyletang/rust-sfml/commit/663b5f871bf5015ebe7f91aac0f6b365eafed26a

**Comment by crumblingstatue** [comment]
The new behavior is to panic on OOM instead of returning Option. Closing.
